language: node_js
node_js:
  - "13"
  - "14"
  - "15"
  - "16"
sudo: false
before_script:
  - npm install && npm install coveralls mocha-lcov-reporter --save-dev
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: always
